name: bon-site to GitHub Pages
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
jobs:
  build-html:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Checkout this repo
      - uses: actions/checkout@v3 
      
      # Build the preview.html file from the rocrate.json
      - name: Rocrate-to-pages build
        uses: vliz-be-opsci/space-to-pages@latest
        with:
          repo_path: https://github.com/{org}/{repo} #replace {org} by organisation and {repo} by the current repo
          #base_uri: https://${{ github.repository_owner }}.github.io/${{ github.repository }}
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages 
        
